/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J
// Component: wa2O1Rx8yCvZ

import * as React from "react";
import { DefaultHomepageProps } from "./PlasmicHomepage"; // plasmic-import: wa2O1Rx8yCvZ/render

import { ClientHomepage } from "../../../src/app/home/page-client"; // plasmic-import: wa2O1Rx8yCvZ/rscClient

const $$ = {};

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

import type { ParamsRecord, PlasmicPageProps } from "@plasmicapp/react-web";

function mkPathFromRouteAndParams(route: string, params: ParamsRecord) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

export async function makeAppRouterPageCtx({
  params,
  searchParams
}: PlasmicPageProps) {
  const pageRoute = "/home";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);

  const ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: {}
  };
  return ctx;
}

export type PlasmicHomepageServerProps = DefaultHomepageProps &
  PlasmicPageProps;

export function PlasmicHomepageServer(props: PlasmicHomepageServerProps) {
  return <ClientHomepage {...props} />;
}
