/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3RVpz8tf8oHM2jiuGYHU8J
// Component: cz_5_nedk6OS

import * as React from "react";
import { DefaultSignupProps } from "./PlasmicSignup"; // plasmic-import: cz_5_nedk6OS/render

import { ClientSignup } from "../../../src/app/signup/page-client"; // plasmic-import: cz_5_nedk6OS/rscClient

const $$ = {};

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "signup",

    openGraph: {
      title: "signup"
    },
    twitter: {
      card: "summary" as const,
      title: "signup"
    }
  };
}

import type { ParamsRecord, PlasmicPageProps } from "@plasmicapp/react-web";

function mkPathFromRouteAndParams(route: string, params: ParamsRecord) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

export async function makeAppRouterPageCtx({
  params,
  searchParams
}: PlasmicPageProps) {
  const pageRoute = "/signup";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);

  const ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: {}
  };
  return ctx;
}

export type PlasmicSignupServerProps = DefaultSignupProps & PlasmicPageProps;

export function PlasmicSignupServer(props: PlasmicSignupServerProps) {
  return <ClientSignup {...props} />;
}
